### Register user
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "email": "john2.doe@example.com",
  "password": "password2",
  "phone": "1234567890",
  "role": "ADMIN"
}

### Login user
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password1"
}

